# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listChosenBox = QtWidgets.QComboBox(self.centralwidget)
        self.listChosenBox.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.listChosenBox.setObjectName("listChosenBox")
        self.confirmBtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmBtn.setGeometry(QtCore.QRect(170, 20, 31, 31))
        self.confirmBtn.setObjectName("confirmBtn")
        self.mainText = QtWidgets.QLabel(self.centralwidget)
        self.mainText.setGeometry(QtCore.QRect(10, 110, 391, 111))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.mainText.setFont(font)
        self.mainText.setAlignment(QtCore.Qt.AlignCenter)
        self.mainText.setObjectName("mainText")
        self.meanText = QtWidgets.QLabel(self.centralwidget)
        self.meanText.setGeometry(QtCore.QRect(20, 220, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.meanText.setFont(font)
        self.meanText.setText("")
        self.meanText.setAlignment(QtCore.Qt.AlignCenter)
        self.meanText.setWordWrap(True)
        self.meanText.setObjectName("meanText")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(200, 20, 31, 31))
        self.resetBtn.setObjectName("resetBtn")
        self.showCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.showCheck.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.showCheck.setChecked(True)
        self.showCheck.setObjectName("showCheck")
        self.pronText = QtWidgets.QLabel(self.centralwidget)
        self.pronText.setGeometry(QtCore.QRect(10, 140, 391, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pronText.setFont(font)
        self.pronText.setText("")
        self.pronText.setAlignment(QtCore.Qt.AlignCenter)
        self.pronText.setObjectName("pronText")
        self.currentlcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.currentlcd.setGeometry(QtCore.QRect(320, 20, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.currentlcd.setFont(font)
        self.currentlcd.setObjectName("currentlcd")
        self.nextlcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.nextlcd.setGeometry(QtCore.QRect(550, 20, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nextlcd.setFont(font)
        self.nextlcd.setObjectName("nextlcd")
        self.shuffleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.shuffleBtn.setGeometry(QtCore.QRect(230, 20, 31, 31))
        self.shuffleBtn.setObjectName("shuffleBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.confirmBtn.setText(_translate("MainWindow", "√"))
        self.mainText.setText(_translate("MainWindow", "Start Reciting Word!"))
        self.resetBtn.setText(_translate("MainWindow", "R"))
        self.showCheck.setText(_translate("MainWindow", "Show Meaning"))
        self.shuffleBtn.setText(_translate("MainWindow", "S"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
